---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kachiprojectapp"
  namespace: "default"
  labels:
    app: "kachiprojectapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "kachiprojectapp"
  template:
    metadata:
      labels:
        app: "kachiprojectapp"
    spec:
      containers:
      - name: "dustudentmeetupv2-sha256-1"
        image: "australia-southeast2-docker.pkg.dev/sit737-23t1-okorie-158836a/kachisit73710d/dustudentmeetupv2@sha256:0c469048cf85f06c02a6caa088959d954b898d30c6893283709ccb3d4b3f9b42"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "kachiprojectapp-hpa-jb6b"
  namespace: "default"
  labels:
    app: "kachiprojectapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "kachiprojectapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
